---
# These task installs and enables apache on webservers
- name: ensure apache,php related packages are installed
  apt: 
    name={{ item }} 
    state=present
#    with_items:
  loop:
    - apache2
    - php
    - php-mysql

- name: ensure apache is running
  service: 
    name=apache2 
    state=running 
    enabled=yes

- name: copy files to document root
  copy: 
    src=cloud.png 
    dest=/var/www/html/cloud.png

- name: copy application code to document root
  template: 
    src=index.php.j2 
    dest=/var/www/html/index.php
  notify: 
    restart apache2
