---
# These task installs and enables apache on webservers
- name: ensure mysql is installed
  apt: 
    name={{ item }} 
    state=present
#  with_items:
  loop:
   - mysql-server
   - python3-pymysql
#   - MySQL-python

- name: ensure mysql is running
  service: 
    name=mysqld 
    state=started 
    enabled=yes

- name: create application database
  mysql_db: 
    name={{ item }} state=present
  with_items:
    - ansible_db01
    - ansible_db02

- name: create application user
  mysql_user: 
    name={{ dbuser }} 
    password={{ dbpassword }} 
    priv=*.*:ALL 
    state=present
